name: Evening Greeting
  
on:
    schedule:
      - cron: '06 11 * * 1-5'
    workflow_dispatch:

jobs:
    push-evening:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - run: pip install requests chinesecalendar
        - run: python evening.py
