name: Noon News
  
on:
    schedule:
      - cron: '0 4 * * 1-5'
    workflow_dispatch:
    
jobs:
    push-news:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with: 
            python-version: '3.11'
        - run: pip install requests
        - run: python zhihu_hot.py
        
