name: Daily Weather Push

on:
    schedule:
      - cron: '0 1 * * *'
      - cron: '0 7 * * *'
    workflow_dispatch:

jobs:
    push-weather:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 1 * * *'
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install dependencies
          run: pip install requests lunardate
        - name: Run weather script
          run: python weather.py
          env:
            QWEATHER_KEY: ${{ secrets.QWEATHER_KEY }}

    push-london:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 7 * * *'
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install dependencies
          run: pip install requests
        - name: Run London weather script
          run: python london_weather.py

